### PR TITLE
v1.1.4

### LINKED ISSUE #10: Add random ID generator module
- ID includes letters and numbers.
- Customisable lengths

### PR DESCRIPTION
**Pull request by wdhdev**
# v1.1.4
A release adding new modules and improving the package overall.

## Changelog
- Make README look nicer
- Update package keywords
- Add `removeDuplicates` submodule to `util`
- Fix bug in `numToStr` if input was `0` it would throw error
- Add `numToBool` submodule
- Move type converters to separate module named `types`
- Adds `id` module
  - New dependency `nanoid`

### Linked Issues / Pull Requests
adds #10 
adds #25

### CODE REVIEW

**Comment by wdhdev** [comment]
@norisurgit Hey, would you be able to write some code examples for the [docs](https://docs.easyscript.dev)?

**Comment by norisurgit** [comment]
> @norisurgit Hey, would you be able to write some code examples for the [docs](https://docs.easyscript.dev)?

Yeah, sure

**Comment by wdhdev** [comment]
> > @norisurgit Hey, would you be able to write some code examples for the [docs](https://docs.easyscript.dev)?
> 
> Yeah, sure

If you want, just send them here.

**Comment by norisurgit** [comment]
```js
const dirtyArray = [
    ""/** Empty string */,
    "I am a string", "I am a string", /* Duplicate strings */
    0, 0, -50, -50, 5, 5 /** Numbers */,
    [1, "Another string", 5], [10, [44]],/** Arrays */
    {}, /** Empty objects */,
    { key: "value", key2: "value 2" }, /** Object */
    () => { }, /** Functions  */
    , null /** Null */
    , undefined /** Undefined */
]

console.log(removeDuplicates(dirtyArray, true, true["numeric", "lengthwise", "alphabetic"]))
// Clean falsy values, delete useless data, retrieve data from arrays and sort then remove duplicates
// ['I am a string', -50, 0, 1, 5, 'Another string', 10, 44, { key: 'value', key2: 'value 2' }]

console.log(removeDuplicates(dirtyArray, false, false, "none")) 
// Sames as console.log(removeDuplicates(dirtyArray))
// Remove duplicate values only

// [ '', 0, 'I am a string', -50, 5, [1, 'Another string', 5], [10, [44]], {}, undefined, { key: 'value', key2: 'value 2' }, [Function(anonymous)], null ]
```

**Comment by norisurgit** [comment]
The code is also self-documenting (JSDoc) so you will get linting as you type

**Comment by wdhdev** [comment]
> The code is also self-documenting (JSDoc) so you will get linting as you type

Thank you!

**Comment by norisurgit** [comment]
Sure, I’ll get to it when I can. On Jan 10, 2023, at 00:39, William Harrison ***@***.***> wrote:﻿

The code is also self-documenting (JSDoc) so you will get linting as you type

Thank you! I'm not sure if it would be too much to ask, but could you possibly open a PR pointing to the release/v1.1.4 branch, making the modules self documenting? Most are just one input.

**Comment by wdhdev** [comment]
> Sure, I’ll get to it when I can. On Jan 10, 2023, at 00:39, William Harrison ***@***.***> wrote:﻿ The code is also self-documenting (JSDoc) so you will get linting as you type Thank you! I'm not sure if it would be too much to ask, but could you possibly open a PR pointing to the release/v1.1.4 branch, making the modules self documenting? Most are just one input. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

Thank you.

**Pull request merged**
